### ISSUE TITLE
WALC not working since 6th August. Says it needs update Google Chrome

### ISSUE THREAD

**Issue by hydrosIII** [WAClient/WALC#160] opened 2021-08-06 18:24 UTC
I openned WALC today and i got this message. It must be a change in WhatsApp
![Captura de pantalla de 2021-08-06 13-22-34](https://user-images.githubusercontent.com/7807363/128555387-b12a5044-3109-4469-a97b-c11d356d55b5.png)

**Comment by cstayyab** [comment] 2021-08-07 22:24
Duplicate of #138

**Closed by cstayyab** 2021-08-07 22:24 UTC
Labels: bug
